apiVersion: v1
kind: Pod
metadata:
  labels:
    run: girus
    server: webserver
  name: girus
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  - image: busybox
    name: busybox
    args:
    - sleep
    - "600"
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
