apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /giropops
      name: first-emptydir
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests: 
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: first-emptydir
    emptyDir:
      sizeLimit: 256Mi