# Evitar ao máximo criar replicaset sozinho, criar ele atraves deployment. 
# Pois voce perde alguns managements como rollout do deployment e toda sua estratégia.
# Esse arquivo é mais como exemplo de que existe essa opção.
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: nginx-app
  name: nginx-replicaset
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits:
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: "0.3"
            memory: 128Mi