apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: giropops-senhas
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
  labels:
    name: giropops-senhas
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - giropops-senhas.matheussilveira.dev
    secretName: giropops-senhas-tls
  rules:
  - host: giropops-senhas.matheussilveira.dev
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: giropops-senhas
            port: 
              number: 5000
