apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: giropops-senhas-servicemonitor
  namespace: default
  labels:
    app: giropops-senhas
spec:
  selector:
    matchLabels:
      app: giropops-senhas
  endpoints:
  - port: http
    interval: 30s
