apiVersion: v1
data:
  nginx.conf: |
    events {}

    http {
      server {
        listen 80;
        listen 443 ssl;

        ssl_certificate /etc/nginx/tls/certificate.crt;
        ssl_certificate_key /etc/nginx/tls/private-key.key;

        location / {
          return 200 'Hello, World!';
          add_header Content-Type text/plain;
        }
      }
    }
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
