apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
  labels:
    app: nginx
spec:
  containers:
  - name: giropops-container
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
      - containerPort: 443
    volumeMounts:
      - name: nginx-config-volume
        mountPath: /etc/nginx/nginx.conf
        subPath: nginx.conf
      - name: nginx-tls
        mountPath: /etc/nginx/tls
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
  - name: nginx-tls
    secret:
      secretName: my-web-service-tls-secret
      items:
      - key: tls.crt
        path: certificate.crt
      - key: tls.key
        path: private-key.key
