apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: my-pod
spec:
  containers:
  - name: my-pod
    image: matheuspmsilveira/go-test:5.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
  - name: dockerhub-secret
