apiVersion: v1
kind: Pod
metadata:
  name: giropops-pod
  labels:
    name: giropops-pod
spec:
  containers:
  - name: giropops-pod
    image: nginx
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: password
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
